export const ROUTE_PATHS = {
  HOME: '/',
  SHOP: '/shop',
  PRODUCT_DETAIL: '/product/:slug',
  CATEGORY: '/category/:slug',
  ABOUT: '/about',
  CONTACT: '/contact',
  FAQ: '/faq',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  SHIPPING: '/shipping',
  LEGAL: '/legal',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  VERIFY_EMAIL: '/auth/verify-email',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_CONFIRMATION: '/order/confirmation/:orderId',
  ACCOUNT_DASHBOARD: '/account/dashboard',
  PROFILE: '/account/profile',
  ACCOUNT_PROFILE: '/account/profile',
  ADDRESSES: '/account/addresses',
  ORDERS: '/account/orders',
  ORDER_DETAIL: '/account/orders/:orderId',
  WISHLIST: '/account/wishlist',
  NOTIFICATIONS: '/account/notifications',
  SETTINGS: '/account/settings',
  ADMIN: '/admin',
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_PRODUCT_ANALYTICS: '/admin/analytics/products',
  ADMIN_SALES_ANALYTICS: '/admin/analytics/sales',
  ADMIN_CUSTOMER_ANALYTICS: '/admin/analytics/customers',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_NEW: '/admin/products/new',
  ADMIN_PRODUCT_EDIT: '/admin/products/:id/edit',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_CATEGORY_NEW: '/admin/categories/new',
  ADMIN_CATEGORY_EDIT: '/admin/categories/:id/edit',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_ORDER_DETAIL: '/admin/orders/:orderId',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAIL: '/admin/users/:userId',
  ADMIN_COUPONS: '/admin/coupons',
  ADMIN_COUPON_NEW: '/admin/coupons/new',
  ADMIN_COUPON_EDIT: '/admin/coupons/:id/edit',
  ADMIN_BANNERS: '/admin/banners',
  ADMIN_BANNER_NEW: '/admin/banners/new',
  ADMIN_BANNER_EDIT: '/admin/banners/:id/edit',
  ADMIN_MESSAGES: '/admin/messages',
  ADMIN_ACTIVITY_LOGS: '/admin/activity-logs',
  ADMIN_SETTINGS: '/admin/settings',
  FORBIDDEN: '/403',
  SERVER_ERROR: '/500',
  MAINTENANCE: '/maintenance',
};

/** Build concrete paths from parameterized route templates */
export const buildPath = {
  product: (slug) => `/product/${slug}`,
  category: (slug) => `/category/${slug}`,
  shopCategory: (categoryId) => `/shop?categoryId=${categoryId}`,
  orderConfirmation: (orderId) => `/order/confirmation/${orderId}`,
  orderDetail: (orderId) => `/account/orders/${orderId}`,
  adminProductEdit: (id) => `/admin/products/${id}/edit`,
  adminCategoryEdit: (id) => `/admin/categories/${id}/edit`,
  adminOrderDetail: (orderId) => `/admin/orders/${orderId}`,
  adminUserDetail: (userId) => `/admin/users/${userId}`,
  loginWithRedirect: (path) =>
    `${ROUTE_PATHS.LOGIN}?redirect=${encodeURIComponent(path)}`,
};
