import { ROUTES } from './routes';

export const PUBLIC_ROUTES = {
  HOME: ROUTES.HOME,
  SHOP: ROUTES.SHOP,
  PRODUCT_DETAIL: ROUTES.PRODUCT_DETAIL,
  CATEGORY: ROUTES.CATEGORY,
  ABOUT: ROUTES.ABOUT,
  CONTACT: ROUTES.CONTACT,
  FAQ: ROUTES.FAQ,
  TERMS: ROUTES.TERMS,
  PRIVACY: ROUTES.PRIVACY,
};

export const AUTH_ROUTES = {
  LOGIN: ROUTES.LOGIN,
  REGISTER: ROUTES.REGISTER,
  VERIFY_EMAIL: ROUTES.VERIFY_EMAIL,
  FORGOT_PASSWORD: ROUTES.FORGOT_PASSWORD,
  RESET_PASSWORD: ROUTES.RESET_PASSWORD,
};

export const CUSTOMER_ROUTES = {
  DASHBOARD: ROUTES.ACCOUNT_DASHBOARD,
  PROFILE: ROUTES.ACCOUNT_PROFILE,
  ADDRESSES: ROUTES.ACCOUNT_ADDRESSES,
  ORDERS: ROUTES.ACCOUNT_ORDERS,
  ORDER_DETAIL: ROUTES.ACCOUNT_ORDER_DETAIL,
  WISHLIST: ROUTES.ACCOUNT_WISHLIST,
  NOTIFICATIONS: ROUTES.ACCOUNT_NOTIFICATIONS,
  SETTINGS: ROUTES.ACCOUNT_SETTINGS,
};

export const ADMIN_ROUTES = {
  DASHBOARD: ROUTES.ADMIN,
  PRODUCT_ANALYTICS: ROUTES.ADMIN_PRODUCT_ANALYTICS,
  SALES_ANALYTICS: ROUTES.ADMIN_SALES_ANALYTICS,
  CUSTOMER_ANALYTICS: ROUTES.ADMIN_CUSTOMER_ANALYTICS,
  PRODUCTS: ROUTES.ADMIN_PRODUCTS,
  PRODUCT_NEW: ROUTES.ADMIN_PRODUCT_NEW,
  PRODUCT_EDIT: ROUTES.ADMIN_PRODUCT_EDIT,
  CATEGORIES: ROUTES.ADMIN_CATEGORIES,
  CATEGORY_NEW: ROUTES.ADMIN_CATEGORY_NEW,
  CATEGORY_EDIT: ROUTES.ADMIN_CATEGORY_EDIT,
  ORDERS: ROUTES.ADMIN_ORDERS,
  ORDER_DETAIL: ROUTES.ADMIN_ORDER_DETAIL,
  USERS: ROUTES.ADMIN_USERS,
  USER_DETAIL: ROUTES.ADMIN_USER_DETAIL,
  COUPONS: ROUTES.ADMIN_COUPONS,
  COUPON_NEW: ROUTES.ADMIN_COUPON_NEW,
  COUPON_EDIT: ROUTES.ADMIN_COUPON_EDIT,
  BANNERS: ROUTES.ADMIN_BANNERS,
  BANNER_NEW: ROUTES.ADMIN_BANNER_NEW,
  BANNER_EDIT: ROUTES.ADMIN_BANNER_EDIT,
  MESSAGES: ROUTES.ADMIN_MESSAGES,
  SETTINGS: ROUTES.ADMIN_SETTINGS,
};

export const ERROR_ROUTES = {
  FORBIDDEN: ROUTES.FORBIDDEN,
  SERVER_ERROR: ROUTES.SERVER_ERROR,
  MAINTENANCE: ROUTES.MAINTENANCE,
};
